### ISSUE TITLE
yolo_body() error

### ISSUE THREAD

**Issue by shadySource** [allanzelener/YAD2K#20]
### Error Description:
Calling yolo_body twice causes an error:

File "/home/user/YAD2K/yad2k/models/keras_yolo.py", line 52, in yolo_body
```python
conv13 = darknet.get_layer('leaky_re_lu_13').output
```
AttributeError: 'NoneType' object has no attribute 'output'

### Example Program:
```python
from keras.layers import Input
from yad2k.models.keras_yolo import yolo_body

anchors =[((1,2), (3,4)), ((5,6), (7,8))]
class_names = ['cat', 'dog', 'moose']

image_input = Input(shape=(416, 416, 3))

yolo_model = yolo_body(image_input, len(anchors), len(class_names))
yolo_model = yolo_body(image_input, len(anchors), len(class_names))
```

### Thoughts:
I added ```darknet.summary() ``` before the line it errors on, and first conv layer has the name 'conv2d_24', so the names are not resetting for some reason...

**Comment by allanzelener** [comment]
Yes, this is the expected behavior with symbolic graph libraries for deep learning like Tensorflow. Every time you call the constructor for a symbolic variable you create a new instance in the symbolic graph. 

The issue here is that it's hardcoded to use the layer with the name `leaky_re_lu_13` which exists in the first model but not the second. A better solution is to determine the index of that layer into `darknet.layers` and hardcode the index instead of the specific name.

However I think that Keras/Tensorflow may use variable names for loading/saving model weights so depending on your task using multiple models in one session can have some unintended consequences so you should be careful with that.
